<a href="https://colab.research.google.com/github/santiagovillamizarjaimes-collab/Primer-corte/blob/main/m%C3%B3dulos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

Creando arreglos

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]]

In [ ]:
lista = [1, 2, 3]
arr = np.array([1, 2, 3])

In [ ]:
lista*2

[1, 2, 3, 1, 2, 3]

In [ ]:
arr*2

array([2, 4, 6])

In [ ]:
print(arr.shape,
      arr.ndim,
      arr.dtype,
      arr.size)

(3,) 1 int64 3

Arreglos espaciales:

In [ ]:
print(np.zeros((2, 3)),
      np.ones((2,2)),
      np.eye(3),
      np.arange(0, 10, 2),
      np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]

Indexación

In [ ]:
a = np.array([10, 20, 30, 40])
print(a[0], a[-1], a[1:3])

10 40 [20 30]

Indexación de matrices:

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[0, 1], b[:1], b[1,:])

2 [[1 2 3]] [4 5 6]

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [ ]:
a*b

array([ 4, 10, 18])

In [ ]:
[x * 2 for x in lista]

[2, 4, 6]

In [ ]:
arr * 2

array([2, 4, 6])

In [ ]:
b = np.array([1, 2, 3, 4])

In [ ]:
print(np.mean(b), np.median(b), np.std(b), np.sum(b), np.min(b), np.max(b))

2.5 2.5 1.118033988749895 10 1 4

Manipulación de arreglos

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([a, a])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate(a.reshape(2, 3))

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.reshape(2, 3).flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [ ]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [ ]:
print(np. random.rand(10))
print(np.random.randint(0, 10))
print(np.random.randn(3))

[0.27258959 0.15831904 0.00519917 0.4054954  0.34455655 0.1217357
 0.64323577 0.17682735 0.88530703 0.27541271]
2
[-0.34670453  0.11977975  0.24758847]

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a[a> 3]

array([4, 5])

In [ ]:
a[(a > 2) & (a < 5)]

array([3, 4])

In [ ]:
np.where(a > 3, 1, 0)

array([0, 0, 0, 1, 1])

In [ ]:
np.where(a <= 3, 2, 3)

array([2, 2, 2, 3, 3])

Ejercicio

In [ ]:
arreglo = np.arange(1, 11)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arreglo*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
c = np.arange(1, 10).reshape(3, 3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.mean(arreglo))
print(np.std(arreglo))

5.5
2.8722813232690143

In [ ]:
condicional = np.where(arreglo > 7, 1, arreglo)
condicional

array([1, 2, 3, 4, 5, 6, 7, 1, 1, 1])

Ahora con pandas

In [1]:
import pandas as pd

In [2]:
s = pd.Series([10, 20, 30])
s

0    10
1    20
2    30
dtype: int64

In [3]:
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ["Bogota", "Medellin", "Cali", "Bogota"],
    'edad': [23, 30, 35, 28],
    'Salarios': [1500, 2000, 3000, 2500]
})
df

   nombre    ciudad  edad  Salarios
0     Ana    Bogota    23      1500
1    Luis  Medellin    30      2000
2  Carlos      Cali    35      3000
3   Marta    Bogota    28      2500

In [4]:
df.head(2)

  nombre    ciudad  edad  Salarios
0    Ana    Bogota    23      1500
1   Luis  Medellin    30      2000

In [5]:
df.tail(2)

   nombre  ciudad  edad  Salarios
2  Carlos    Cali    35      3000
3   Marta  Bogota    28      2500

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nombre    4 non-null      object
 1   ciudad    4 non-null      object
 2   edad      4 non-null      int64
 3   Salarios  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [7]:
df.describe()

            edad     Salarios
count   4.000000     4.000000
mean   29.000000  2250.000000
std     4.966555   645.497224
min    23.000000  1500.000000
25%    26.750000  1875.000000
50%    29.000000  2250.000000
75%    31.250000  2625.000000
max    35.000000  3000.000000

In [9]:
df.shape

(4, 4)

In [11]:
salario_promedio = df['Salarios'].mean()
print(f"El salario promedio es: {salario_promedio}")

El salario promedio es: 2250.0

In [12]:
df['edad']

0    23
1    30
2    35
3    28
Name: edad, dtype: int64

In [13]:
df[['nombre', 'edad']]

   nombre  edad
0     Ana    23
1    Luis    30
2  Carlos    35
3   Marta    28

In [14]:
df[df['edad']> 25]

   nombre    ciudad  edad  Salarios
1    Luis  Medellin    30      2000
2  Carlos      Cali    35      3000
3   Marta    Bogota    28      2500

In [15]:
df[(df['edad']> 20) & (df['edad']< 40)]

   nombre    ciudad  edad  Salarios
0     Ana    Bogota    23      1500
1    Luis  Medellin    30      2000
2  Carlos      Cali    35      3000
3   Marta    Bogota    28      2500

In [27]:
data = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
    'edad': [23, np.nan, 35, 23, 40],
    'salario': [1000, 2000, None, 1000, 5000],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']
}
data

{'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
 'edad': [23, nan, 35, 23, 40],
 'salario': [1000, 2000, None, 1000, 5000],
 'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']}

In [28]:
data1 = pd.DataFrame(data)
data1

   nombre  edad  salario    ciudad
0     Ana  23.0   1000.0    Bogotá
1    Luis   NaN   2000.0  Medellín
2  Carlos  35.0      NaN      Cali
3     Ana  23.0   1000.0    Bogotá
4    None  40.0   5000.0      Cali

In [29]:
data1.isnull()

   nombre   edad  salario  ciudad
0   False  False    False   False
1   False   True    False   False
2   False  False     True   False
3   False  False    False   False
4    True  False    False   False

In [30]:
data1.isnull().sum()

nombre     1
edad       1
salario    1
ciudad     0
dtype: int64

In [31]:
data2 = data1.dropna()
data2

  nombre  edad  salario  ciudad
0    Ana  23.0   1000.0  Bogotá
3    Ana  23.0   1000.0  Bogotá

In [32]:
data1.dropna(subset=['salario'])

  nombre  edad  salario    ciudad
0    Ana  23.0   1000.0    Bogotá
1   Luis   NaN   2000.0  Medellín
3    Ana  23.0   1000.0    Bogotá
4   None  40.0   5000.0      Cali

In [34]:

data1["nombre"] = data1['nombre'].fillna('Desconocido')
data1

        nombre  edad  salario    ciudad
0          Ana  23.0   1000.0    Bogotá
1         Luis   NaN   2000.0  Medellín
2       Carlos  35.0      NaN      Cali
3          Ana  23.0   1000.0    Bogotá
4  Desconocido  40.0   5000.0      Cali

In [36]:
data1['ciudad'] = data1['ciudad'].replace('Bogotá', 'BOGOTA')
data1

        nombre  edad  salario    ciudad
0          Ana  23.0   1000.0    BOGOTA
1         Luis   NaN   2000.0  Medellín
2       Carlos  35.0      NaN      Cali
3          Ana  23.0   1000.0    BOGOTA
4  Desconocido  40.0   5000.0      Cali

In [38]:
data4 = data1["ciudad"].drop_duplicates()
data4

0      BOGOTA
1    Medellín
2        Cali
Name: ciudad, dtype: object

In [42]:
data5 = {
    'nombre': ['Ana', 'Luis', 'Ana', 'Carlos', 'Luis'],
    'edad': [23, 25, 23, 35, 30],
    'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellin', 'Cali']
}
data5= pd.DataFrame(data5)
data5

   nombre  edad    ciudad
0     Ana    23    Bogotá
1    Luis    25      Cali
2     Ana    23    Bogotá
3  Carlos    35  Medellin
4    Luis    30      Cali

In [43]:
data6 = data5.drop_duplicates()
data6

   nombre  edad    ciudad
0     Ana    23    Bogotá
1    Luis    25      Cali
3  Carlos    35  Medellin
4    Luis    30      Cali

In [44]:
dfn = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'nombre': ['Ana', 'Luis', 'CARLOS', 'ana'],
    'ciudad': [23, 30, 35, 28],
    'salario': [1000, 2000, 3000, 1500],
    'ciudad': ['Bogotá', 'Cali', 'Bogota', 'Medellin']
})
dfn

   id  nombre    ciudad  salario
0   1     Ana    Bogotá     1000
1   2    Luis      Cali     2000
2   3  CARLOS    Bogota     3000
3   4     ana  Medellin     1500