<a href="https://colab.research.google.com/github/santiagovillamizarjaimes-collab/Primer-corte/blob/main/semana9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Manejo de módulos integrados**

Más usados por nosotros Numpy y Pandas

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4])
b= np.array([[1, 2], [3, 4], [1, 2]])
print(a)
print(b)

[1 2 3 4]
[[1 2]
 [3 4]
 [1 2]]

In [9]:
b*2

array([[2, 4],
       [6, 8],
       [2, 4]])

In [5]:
lista = [1, 2, 3]
arr= np.array([1, 2, 3])

In [6]:
lista*2

[1, 2, 3, 1, 2, 3]

In [10]:
arr*2 # Hay una interpretación de los arreglos de tipo numpy más apegados a lo que vemos en los objetos mátematicos como los vectores

array([2, 4, 6])

In [13]:
arr.shape

(3,)

In [16]:
b.shape # Arrego de tres componentes cada una con dos elementos

(3, 2)

In [17]:
arr.ndim

1

In [19]:
b.ndim #Número de elementos por cada componente

2

In [20]:
b.dtype # El tipo de elementos que tiene cada una de las entradas

dtype('int64')

In [22]:
b.size # La cantidad de elementos en todas las componentes

6

In [23]:
np.zeros((2, 3)) # Todo lleno de ceros: 2 componentes y tres elementos por componentes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,3)) # Todo lleno de ceros: 1 componentes y tres elementos por componentes

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.eye(3) # La matriz identidad de una matriz cuadrada de tamaño 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.arange(0, 10, 2) # Del 0 sin hasta el 10 (sin tomar el 10), separado por 2

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(0, 3, 5) #Toma cinco elemetos equdistantes entre el cero y el 3

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [31]:
arry = np.array([10, 20, 30, 40])
arry

array([10, 20, 30, 40])

In [32]:
arry[-1]

np.int64(40)

In [36]:
arry[0: 2] # Tomando del índice 0 al 2 (sin tomar el 2)

array([10, 20])

In [37]:
matri = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
matri[0, 1] # El índice uno de la 0ésima fila

np.int64(2)

In [47]:
matri[:,1] # :, 1 = la primera columna

array([2, 5])

In [48]:
matri[1,:] # 1, : = La primera fila

array([4, 5, 6])

In [49]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [50]:
a * b # Producto de Hadamar de dos arreglos

array([ 4, 10, 18])

In [51]:
matri1 = np.array([[2, 3, 3], [4,5,6]])
matri1*matri #Producto de Hadamard

array([[ 2,  6,  9],
       [16, 25, 36]])

In [52]:
[x * 2 for x in lista]

[2, 4, 6]

In [56]:
c = np.array([1.65, 1.58, 1.82, 1.70, 1.50, 1.82, 1.74])
print(np.mean(c), np.median(c), np.std(c), np.sum(c), np.min(c), np.max(c))

1.6871428571428573 1.7 0.11093296376181246 11.81 1.5 1.82

Manipulación de arreglos:

In [57]:
d = np.array([1, 2, 3, 4, 5, 6]) # Inicialmente tiene 6 componentes de un elemento cada una
d.reshape(2,3) # Cam,bia a 2 componentes cada una con 3 elementos

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.concatenate(d.reshape(2,3))

array([1, 2, 3, 4, 5, 6])

In [59]:
d.reshape(2, 3). flatten() # Vectoriza la matriz

array([1, 2, 3, 4, 5, 6])

In [61]:
a = np.array([[1,2], [3,4]])
b = np.array([[3, 8], [7, 8]])

np.dot(a, b) #producto

array([[17, 24],
       [37, 56]])

In [63]:
np.linalg.inv(a) # Inversa de una matriz

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [64]:
np.linalg.matrix_transpose(a)

array([[1, 3],
       [2, 4]])

In [68]:
np.random.rand(10) # Genera 10 valosres de una distribución uniforme en el intervalo (0,1)

array([0.43585049, 0.62343523, 0.65798691, 0.25250885, 0.54537458,
       0.89446848, 0.86987637, 0.61888854, 0.89419108, 0.88362959])

In [109]:
np.random.randint(0,10) # Genera un valor entero entre 0 y el entero anterior al 10

8

In [112]:
np.random.randn(8) # Genera 8 Valores aleatorios de una distribución normal con media 0 y desviación estándar 1

array([ 2.11243339,  0.24743526,  0.20964909, -0.08157076,  1.49737454,
        0.83687601,  0.14509946,  0.82322523])

In [113]:
e = np.array([1,2,3,4,5]) #Filtrado y condiciones
f = e[e > 3]
f

array([4, 5])

In [114]:
e[(e > 2) & (e < 5)] # Note que el "y" es así &. El o es así |

array([3, 4])

In [115]:
np.where(e > 3, 1, 0)

array([0, 0, 0, 1, 1])

Actividad

In [118]:
arreglo = np.arange(1, 11)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arreglo*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [123]:
c = np.arange(1, 10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
print(np.mean(arreglo))
print(np.std(arreglo))

5.5
2.8722813232690143

In [125]:
condicional = np.where(arreglo > 7, 1, arreglo)
condicional

array([1, 2, 3, 4, 5, 6, 7, 1, 1, 1])

# **Pandas**

In [128]:
import pandas as pd

In [129]:
s = pd.Series([10,20, 30]) # Vector columna
s

0    10
1    20
2    30
dtype: int64

In [131]:
df = pd.DataFrame({
    'nombre': ['Ana', 'Luis', 'Carlos', 'Marta'],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá'],
    'edad': [23, 30, 35, 28],
    'salario': [1500, 2000, 3000, 2500]
}) # creando data.frames
df

   nombre    ciudad  edad  salario
0     Ana    Bogotá    23     1500
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [136]:
df.head(2)

  nombre    ciudad  edad  salario
0    Ana    Bogotá    23     1500
1   Luis  Medellín    30     2000

In [137]:
df.tail(2)

   nombre  ciudad  edad  salario
2  Carlos    Cali    35     3000
3   Marta  Bogotá    28     2500

In [138]:
df.info() # tipos de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   4 non-null      object
 1   ciudad   4 non-null      object
 2   edad     4 non-null      int64
 3   salario  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [140]:
df.describe() # Estadísticas descriptivas basicas para variables cuantitativas

            edad      salario
count   4.000000     4.000000
mean   29.000000  2250.000000
std     4.966555   645.497224
min    23.000000  1500.000000
25%    26.750000  1875.000000
50%    29.000000  2250.000000
75%    31.250000  2625.000000
max    35.000000  3000.000000

In [141]:
df.shape  #(filas, columnas)

(4, 4)

In [144]:
df[['nombre', 'edad']] # Selección de columnas utilizando una lista con los respectivos nombres

   nombre  edad
0     Ana    23
1    Luis    30
2  Carlos    35
3   Marta    28

In [145]:
df[df['edad']> 25] # Selección de filas

   nombre    ciudad  edad  salario
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [146]:
df[(df['edad'] > 20) & (df['edad'] < 40)]

   nombre    ciudad  edad  salario
0     Ana    Bogotá    23     1500
1    Luis  Medellín    30     2000
2  Carlos      Cali    35     3000
3   Marta    Bogotá    28     2500

In [147]:
data = {
    'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
    'edad': [23, np.nan, 35, 23, 40],
    'salario': [1000, 2000, None, 1000, 5000],
    'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']
}
data

{'nombre': ['Ana', 'Luis', 'Carlos', 'Ana', None],
 'edad': [23, nan, 35, 23, 40],
 'salario': [1000, 2000, None, 1000, 5000],
 'ciudad': ['Bogotá', 'Medellín', 'Cali', 'Bogotá', 'Cali']}

In [148]:
data1 = pd.DataFrame(data)
data1

   nombre  edad  salario    ciudad
0     Ana  23.0   1000.0    Bogotá
1    Luis   NaN   2000.0  Medellín
2  Carlos  35.0      NaN      Cali
3     Ana  23.0   1000.0    Bogotá
4    None  40.0   5000.0      Cali

In [150]:
data1.isnull().sum() # Suma los valores por columna u1 si es faltante 0 si no

nombre     1
edad       1
salario    1
ciudad     0
dtype: int64

In [151]:
data2 = data1.dropna() # Elimina las filas con valores faltantes
data2

  nombre  edad  salario  ciudad
0    Ana  23.0   1000.0  Bogotá
3    Ana  23.0   1000.0  Bogotá

In [152]:
data1.dropna(subset=['salario']) # Se eliminan las filas con valores faltantes únicamente en la columna salario

  nombre  edad  salario    ciudad
0    Ana  23.0   1000.0    Bogotá
1   Luis   NaN   2000.0  Medellín
3    Ana  23.0   1000.0    Bogotá
4   None  40.0   5000.0      Cali

In [157]:
data1['edad'] = data1['edad'].fillna(data1['edad'].mean()) # Se reemplazan los valores faltantes por la media
data1['nombre'] = data1['nombre'].fillna('Desconocido')
data1

        nombre   edad  salario    ciudad
0          Ana  23.00   1000.0    BOGOTA
1         Luis  30.25   2000.0  Medellín
2       Carlos  35.00      NaN      Cali
3          Ana  23.00   1000.0    BOGOTA
4  Desconocido  40.00   5000.0      Cali

In [156]:
data1['ciudad'] = data1['ciudad'].replace('Bogotá', 'BOGOTA')
data1

        nombre   edad  salario    ciudad
0          Ana  23.00   1000.0    BOGOTA
1         Luis  30.25   2000.0  Medellín
2       Carlos  35.00      NaN      Cali
3          Ana  23.00   1000.0    BOGOTA
4  Desconocido  40.00   5000.0      Cali

In [158]:
data4 = data1["ciudad"].drop_duplicates() # Elimina los valores duplicados
data4

0      BOGOTA
1    Medellín
2        Cali
Name: ciudad, dtype: object

In [163]:
data5 = {
    'nombre': ['Ana', 'Luis', 'Ana', 'Carlos', 'Luis'],
    'edad': [23, 30, 23, 35, 30],
    'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín', 'Cali']
}
data5 = pd.DataFrame(data5)
data5

   nombre  edad    ciudad
0     Ana    23    Bogotá
1    Luis    30      Cali
2     Ana    23    Bogotá
3  Carlos    35  Medellín
4    Luis    30      Cali

In [164]:
data6 = data5.drop_duplicates() # Elimina las filas duplicadas
data6

   nombre  edad    ciudad
0     Ana    23    Bogotá
1    Luis    30      Cali
3  Carlos    35  Medellín

In [170]:
dfn = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'nombre': [' Ana', 'LUIS ', 'Carlos', 'ana'],
    'edad': [23, 30, 35, 28],
    'salario': [1000, 2000, 3000, 1500],
    'ciudad': ['Bogotá', 'Cali', 'Bogotá', 'Medellín']
})
dfn

   id  nombre  edad  salario    ciudad
0   1     Ana    23     1000    Bogotá
1   2   LUIS     30     2000      Cali
2   3  Carlos    35     3000    Bogotá
3   4     ana    28     1500  Medellín

In [169]:
dfn['salari_anual'] = dfn['salario'] * 12
# áplicar función
dfn['eda_doble'] = dfn['edad'].apply(lambda x: x * 2)
dfn

   id  nombre  edad  salario    ciudad  salari_anual  eda_doble
0   1     Ana    23     1000    Bogotá         12000         46
1   2   LUIS     30     2000      Cali         24000         60
2   3  Carlos    35     3000    Bogotá         36000         70
3   4     ana    28     1500  Medellín         18000         56

In [172]:
dfn = dfn.rename(columns={'edad': 'age'})
dfn

   id  nombre  age  salario    ciudad
0   1     Ana   23     1000    Bogotá
1   2   LUIS    30     2000      Cali
2   3  Carlos   35     3000    Bogotá
3   4     ana   28     1500  Medellín

In [178]:
dfn['nombre'] = dfn['nombre'].str.upper()
dfn['nombre'] = dfn['nombre'].str.strip()
dfn['nombre'] = dfn['nombre'].str.replace('ANA', 'JANA')

In [179]:
dfn

   id  nombre  age  salario    ciudad
0   1    JANA   23     1000    Bogotá
1   2    LUIS   30     2000      Cali
2   3  CARLOS   35     3000    Bogotá
3   4    JANA   28     1500  Medellín

In [182]:
grupo = dfn.groupby('ciudad')['salario'].mean()
grupo

ciudad
Bogotá      2000.0
Cali        2000.0
Medellín    1500.0
Name: salario, dtype: float64

In [185]:
ordenado = dfn.sort_values(by='age')
ordenado

   id  nombre  age  salario    ciudad
0   1    JANA   23     1000    Bogotá
3   4    JANA   28     1500  Medellín
1   2    LUIS   30     2000      Cali
2   3  CARLOS   35     3000    Bogotá

In [186]:
dfn1 = pd.DataFrame({
    'id': [1, 2, 3, 4]
    'departamento' :['Ventas', 'IT', 'RRHH', 'Marketing']
})
merge = pd.merge(dfn, dfn1, on='id')
merge

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2624663746.py, line 2)